#!/usr/bin/env python3
"""Give pre-Oreo guest bytecode an API-25 Build.VERSION identity.

Changing the helper app's targetSdk influences Android compatibility gates, but it
never changes Build.VERSION.SDK_INT read by legacy Java/Kotlin code. Process-global
spoofing is unsafe because BlackBox itself must see the real host SDK for Binder and
parcel signatures. This patch therefore rewrites only DEX string references inside
an imported target<=25 APK and appends a tiny API-25 shim DEX generated by CI.
"""
from __future__ import annotations

import sys
from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count == 0:
        if new in text:
            print(f"[guest-sdk] {label}: already applied")
            return text
        raise SystemExit(f"[guest-sdk] {label}: source pattern not found")
    if count != 1:
        raise SystemExit(f"[guest-sdk] {label}: expected one match, found {count}")
    print(f"[guest-sdk] {label}: applied")
    return text.replace(old, new, 1)


def write_translator(root: Path) -> None:
    path = root / "Bcore/src/main/java/top/niunaijun/blackbox/utils/compat/LegacyGuestSdkCompat.java"
    source = r'''package top.niunaijun.blackbox.utils.compat;

import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.security.MessageDigest;
import java.util.Enumeration;
import java.util.Locale;
import java.util.zip.Adler32;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.util.zip.ZipOutputStream;

import top.niunaijun.blackbox.BlackBoxCore;
import top.niunaijun.blackbox.utils.Slog;

/** Guest-only Build.VERSION representation translation. */
public final class LegacyGuestSdkCompat {
    private static final String TAG = "LegacyGuestSdkCompat";
    private static final int PROFILE_SDK = 25;
    private static final String SHIM_ASSET = "compat/legacy-build-shim.dex";
    private static final byte[] SOURCE = ascii("Landroid/os/Build$VERSION;");
    private static final byte[] TARGET = ascii("Lappcompat/compat/Version;");

    private LegacyGuestSdkCompat() {
    }

    public static final class Result {
        public final boolean translated;
        public final int dexFilesPatched;
        public final int referencesPatched;
        public final String shimEntry;

        Result(boolean translated, int dexFilesPatched, int referencesPatched, String shimEntry) {
            this.translated = translated;
            this.dexFilesPatched = dexFilesPatched;
            this.referencesPatched = referencesPatched;
            this.shimEntry = shimEntry;
        }
    }

    public static Result translateIfLegacy(File apk) {
        if (apk == null || !apk.isFile() || apk.length() <= 0) return empty();
        if (SOURCE.length != TARGET.length) {
            throw new IllegalStateException("Guest SDK descriptors must be equal length");
        }
        try {
            PackageInfo info = BlackBoxCore.getPackageManager()
                    .getPackageArchiveInfo(apk.getAbsolutePath(), 0);
            if (info == null || info.applicationInfo == null
                    || info.applicationInfo.targetSdkVersion > PROFILE_SDK) {
                return empty();
            }
            return translate(apk);
        } catch (Throwable t) {
            // Translation is a compatibility enhancement. Never make an otherwise
            // runnable guest uninstallable solely because its ZIP/DEX is unusual.
            Slog.w(TAG, "Guest SDK translation skipped after error: " + t);
            return empty();
        }
    }

    private static Result translate(File apk) throws Exception {
        int maxDexIndex = 0;
        int refs = 0;
        int dexPatched = 0;
        boolean shimAlreadyPresent = false;

        // First pass decides whether we need to repackage at all. This also lets us
        // remove every stale META-INF signature consistently even if those entries
        // occur before classes.dex in ZIP order.
        ZipFile scan = new ZipFile(apk);
        try {
            Enumeration<? extends ZipEntry> entries = scan.entries();
            while (entries.hasMoreElements()) {
                ZipEntry entry = entries.nextElement();
                if (entry.isDirectory() || !isDexName(entry.getName())) continue;
                maxDexIndex = Math.max(maxDexIndex, dexIndex(entry.getName()));
                byte[] data = readAll(scan.getInputStream(entry));
                if (!isDex(data)) continue;
                if (containsString(data, "Lappcompat/compat/Version;")) shimAlreadyPresent = true;
                refs += countString(data, SOURCE);
            }
        } finally {
            scan.close();
        }
        if (refs == 0) return empty();

        File temp = new File(apk.getParentFile(), apk.getName() + ".sdk25.tmp");
        if (temp.exists()) temp.delete();
        int actualRefs = 0;
        ZipFile input = new ZipFile(apk);
        try {
            ZipOutputStream output = new ZipOutputStream(
                    new FileOutputStream(temp, false), 1024 * 1024);
            try {
                Enumeration<? extends ZipEntry> entries = input.entries();
                while (entries.hasMoreElements()) {
                    ZipEntry entry = entries.nextElement();
                    String name = entry.getName();
                    if (entry.isDirectory()) {
                        ZipEntry directory = new ZipEntry(name);
                        directory.setTime(entry.getTime());
                        output.putNextEntry(directory);
                        output.closeEntry();
                        continue;
                    }
                    if (isSignatureArtifact(name)) continue;

                    byte[] data = readAll(input.getInputStream(entry));
                    if (isDexName(name) && isDex(data)) {
                        int changed = replaceDexDescriptor(data);
                        if (changed > 0) {
                            repairDexHeader(data);
                            actualRefs += changed;
                            dexPatched++;
                        }
                    }
                    ZipEntry copied = new ZipEntry(name);
                    copied.setTime(entry.getTime());
                    output.putNextEntry(copied);
                    output.write(data);
                    output.closeEntry();
                }

                String shimName = null;
                if (!shimAlreadyPresent) {
                    shimName = nextDexName(maxDexIndex);
                    InputStream shimInput = BlackBoxCore.getContext().getAssets().open(SHIM_ASSET);
                    byte[] shim;
                    try {
                        shim = readAll(shimInput);
                    } finally {
                        shimInput.close();
                    }
                    if (!isDex(shim)) throw new IllegalStateException("SDK compatibility shim is not DEX");
                    output.putNextEntry(new ZipEntry(shimName));
                    output.write(shim);
                    output.closeEntry();
                }
            } finally {
                output.close();
            }
        } finally {
            input.close();
        }

        if (actualRefs == 0) {
            temp.delete();
            return empty();
        }

        File backup = new File(apk.getParentFile(), apk.getName() + ".sdk25.original");
        if (backup.exists()) backup.delete();
        if (!apk.renameTo(backup)) {
            temp.delete();
            throw new IllegalStateException("Could not stage guest APK for SDK translation");
        }
        try {
            if (!temp.renameTo(apk)) {
                copy(temp, apk);
                temp.delete();
            }
            backup.delete();
        } catch (Throwable t) {
            apk.delete();
            backup.renameTo(apk);
            throw t;
        }

        String shimEntry = shimAlreadyPresent ? null : nextDexName(maxDexIndex);
        Slog.i(TAG, "Translated guest Build.VERSION to API 25: apk=" + apk.getName()
                + " dex=" + dexPatched + " refs=" + actualRefs + " shim=" + shimEntry);
        return new Result(true, dexPatched, actualRefs, shimEntry);
    }

    private static int replaceDexDescriptor(byte[] data) {
        int stringCount = readIntLe(data, 56);
        int stringIds = readIntLe(data, 60);
        if (!validStringTable(data, stringCount, stringIds)) return 0;
        int changed = 0;
        for (int i = 0; i < stringCount; i++) {
            int stringData = readIntLe(data, stringIds + i * 4);
            int payload = skipUleb128(data, stringData);
            if (payload < 0 || payload + SOURCE.length >= data.length) continue;
            if (matches(data, payload, SOURCE) && data[payload + SOURCE.length] == 0) {
                System.arraycopy(TARGET, 0, data, payload, TARGET.length);
                changed++;
            }
        }
        return changed;
    }

    private static int countString(byte[] data, byte[] wanted) {
        int stringCount = readIntLe(data, 56);
        int stringIds = readIntLe(data, 60);
        if (!validStringTable(data, stringCount, stringIds)) return 0;
        int count = 0;
        for (int i = 0; i < stringCount; i++) {
            int stringData = readIntLe(data, stringIds + i * 4);
            int payload = skipUleb128(data, stringData);
            if (payload < 0 || payload + wanted.length >= data.length) continue;
            if (matches(data, payload, wanted) && data[payload + wanted.length] == 0) count++;
        }
        return count;
    }

    private static boolean containsString(byte[] data, String value) {
        return countString(data, ascii(value)) > 0;
    }

    private static boolean validStringTable(byte[] data, int count, int offset) {
        return count >= 0 && offset >= 0
                && ((long) offset + ((long) count * 4L)) <= data.length;
    }

    private static void repairDexHeader(byte[] data) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-1");
        digest.update(data, 32, data.length - 32);
        byte[] signature = digest.digest();
        System.arraycopy(signature, 0, data, 12, 20);

        Adler32 adler = new Adler32();
        adler.update(data, 12, data.length - 12);
        writeIntLe(data, 8, (int) adler.getValue());
    }

    private static int skipUleb128(byte[] data, int offset) {
        if (offset < 0 || offset >= data.length) return -1;
        int pos = offset;
        for (int i = 0; i < 5; i++) {
            if (pos >= data.length) return -1;
            int value = data[pos++] & 0xff;
            if ((value & 0x80) == 0) return pos;
        }
        return -1;
    }

    private static boolean matches(byte[] data, int offset, byte[] wanted) {
        if (offset < 0 || offset + wanted.length > data.length) return false;
        for (int i = 0; i < wanted.length; i++) {
            if (data[offset + i] != wanted[i]) return false;
        }
        return true;
    }

    private static int readIntLe(byte[] data, int offset) {
        if (offset < 0 || offset + 4 > data.length) return -1;
        return (data[offset] & 0xff)
                | ((data[offset + 1] & 0xff) << 8)
                | ((data[offset + 2] & 0xff) << 16)
                | ((data[offset + 3] & 0xff) << 24);
    }

    private static void writeIntLe(byte[] data, int offset, int value) {
        data[offset] = (byte) value;
        data[offset + 1] = (byte) (value >>> 8);
        data[offset + 2] = (byte) (value >>> 16);
        data[offset + 3] = (byte) (value >>> 24);
    }

    private static boolean isDex(byte[] data) {
        return data != null && data.length > 112
                && data[0] == 'd' && data[1] == 'e' && data[2] == 'x' && data[3] == '\n';
    }

    private static boolean isDexName(String name) {
        return name != null && name.matches("classes(\\d*)\\.dex");
    }

    private static int dexIndex(String name) {
        if ("classes.dex".equals(name)) return 1;
        try {
            String digits = name.substring("classes".length(), name.length() - ".dex".length());
            return Integer.parseInt(digits);
        } catch (Throwable ignored) {
            return 1;
        }
    }

    private static String nextDexName(int maxIndex) {
        return "classes" + (Math.max(1, maxIndex) + 1) + ".dex";
    }

    private static boolean isSignatureArtifact(String name) {
        if (name == null) return false;
        String upper = name.toUpperCase(Locale.ROOT);
        if (!upper.startsWith("META-INF/")) return false;
        return upper.endsWith(".RSA") || upper.endsWith(".DSA")
                || upper.endsWith(".EC") || upper.endsWith(".SF")
                || "META-INF/MANIFEST.MF".equals(upper);
    }

    private static byte[] readAll(InputStream input) throws Exception {
        try {
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024 * 1024];
            int read;
            while ((read = input.read(buffer)) >= 0) output.write(buffer, 0, read);
            return output.toByteArray();
        } finally {
            input.close();
        }
    }

    private static void copy(File from, File to) throws Exception {
        FileInputStream input = new FileInputStream(from);
        try {
            FileOutputStream output = new FileOutputStream(to, false);
            try {
                byte[] buffer = new byte[1024 * 1024];
                int read;
                while ((read = input.read(buffer)) >= 0) output.write(buffer, 0, read);
            } finally {
                output.close();
            }
        } finally {
            input.close();
        }
    }

    private static byte[] ascii(String value) {
        try {
            return value.getBytes("UTF-8");
        } catch (java.io.UnsupportedEncodingException impossible) {
            throw new AssertionError(impossible);
        }
    }

    private static Result empty() {
        return new Result(false, 0, 0, null);
    }
}
'''
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")
    print("[guest-sdk] LegacyGuestSdkCompat: written")


def patch_installer(root: Path) -> None:
    path = root / "Bcore/src/main/java/top/niunaijun/blackbox/core/system/pm/BPackageManagerService.java"
    text = path.read_text(encoding="utf-8")
    text = replace_once(
        text,
        "import top.niunaijun.blackbox.utils.compat.PackageParserCompat;",
        "import top.niunaijun.blackbox.utils.compat.PackageParserCompat;\nimport top.niunaijun.blackbox.utils.compat.LegacyGuestSdkCompat;",
        "import guest SDK translator",
    )
    old = '''            PackageInfo packageArchiveInfo = BlackBoxCore.getPackageManager().getPackageArchiveInfo(apkFile.getAbsolutePath(), 0);
            if (packageArchiveInfo == null) {'''
    new = '''            // The helper targetSdk cannot change Build.VERSION.SDK_INT observed by
            // guest bytecode. Translate only target<=25 APK code to the API-25 shim;
            // BlackBox itself keeps the real host SDK for Binder compatibility.
            LegacyGuestSdkCompat.Result guestSdk = LegacyGuestSdkCompat.translateIfLegacy(apkFile);
            if (guestSdk.translated) {
                Slog.i(TAG, "guest SDK profile: refs=" + guestSdk.referencesPatched
                        + " dex=" + guestSdk.dexFilesPatched + " shim=" + guestSdk.shimEntry);
            }

            PackageInfo packageArchiveInfo = BlackBoxCore.getPackageManager().getPackageArchiveInfo(apkFile.getAbsolutePath(), 0);
            if (packageArchiveInfo == null) {'''
    text = replace_once(text, old, new, "translate guest Build.VERSION before package parse")
    path.write_text(text, encoding="utf-8")


def verify(root: Path) -> None:
    compat = root / "Bcore/src/main/java/top/niunaijun/blackbox/utils/compat/LegacyGuestSdkCompat.java"
    pm = (root / "Bcore/src/main/java/top/niunaijun/blackbox/core/system/pm/BPackageManagerService.java").read_text(encoding="utf-8")
    if not compat.is_file():
        raise SystemExit("[guest-sdk] translator source missing")
    source = compat.read_text(encoding="utf-8")
    for invariant in [
        "Landroid/os/Build$VERSION;",
        "Lappcompat/compat/Version;",
        "repairDexHeader",
        "targetSdkVersion > PROFILE_SDK",
        "compat/legacy-build-shim.dex",
    ]:
        if invariant not in source:
            raise SystemExit(f"[guest-sdk] translator invariant missing: {invariant}")
    if "LegacyGuestSdkCompat.translateIfLegacy(apkFile)" not in pm:
        raise SystemExit("[guest-sdk] package-manager integration missing")
    print("[guest-sdk] guest-only Build.VERSION API-25 translation verified")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: patch_guest_sdk_identity.py <NewBlackbox-root>")
    root = Path(sys.argv[1]).resolve()
    write_translator(root)
    patch_installer(root)
    verify(root)


if __name__ == "__main__":
    main()
