package com.appcompat.engine

import android.content.Context
import android.util.Log
import java.io.File
import java.io.FileOutputStream
import java.security.MessageDigest
import java.util.zip.Adler32
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream

/**
 * Rewrites only the guest APK's references to android.os.Build.VERSION so legacy
 * bytecode sees the Android 7.1 compatibility profile instead of the host phone's
 * real SDK. The BlackBox/runtime classes are untouched and continue to see the real
 * SDK, which is required for current Binder signatures and system services.
 *
 * The class descriptor replacement is deliberately byte-for-byte equal length:
 *   Landroid/os/Build$VERSION;  (26 bytes)
 *   Lappcompat/compat/Version;  (26 bytes)
 *
 * That lets us patch DEX string_data_item payloads without moving any DEX offsets.
 * We then repair the SHA-1 signature and Adler32 checksum and append a tiny shim DEX
 * generated by CI. This avoids process-global Build.VERSION mutation.
 */
object LegacyApkTranslator {
    private const val TAG = "AppCompatGuestTranslate"
    private const val SHIM_ASSET = "compat/legacy-build-shim.dex"
    private const val SOURCE_DESCRIPTOR = "Landroid/os/Build\$VERSION;"
    private const val TARGET_DESCRIPTOR = "Lappcompat/compat/Version;"

    data class Result(
        val translated: Boolean,
        val dexFilesPatched: Int,
        val referencesPatched: Int,
        val shimEntry: String?,
    )

    fun translateGuestSdkIdentity(context: Context, apk: File): Result {
        require(SOURCE_DESCRIPTOR.toByteArray(Charsets.UTF_8).size == TARGET_DESCRIPTOR.toByteArray(Charsets.UTF_8).size)
        if (!apk.isFile || apk.length() <= 0L) return Result(false, 0, 0, null)

        val temp = File(apk.parentFile, "${apk.name}.translate.tmp")
        var patchedDexFiles = 0
        var patchedReferences = 0
        var maxDexIndex = 0
        var hasTargetShimClass = false

        try {
            ZipFile(apk).use { input ->
                ZipOutputStream(FileOutputStream(temp, false).buffered(1024 * 1024)).use { output ->
                    val entries = input.entries()
                    while (entries.hasMoreElements()) {
                        val entry = entries.nextElement()
                        val name = entry.name
                        if (entry.isDirectory) {
                            output.putNextEntry(ZipEntry(name).apply { time = entry.time })
                            output.closeEntry()
                            continue
                        }

                        val data = input.getInputStream(entry).use { it.readBytes() }
                        var outData = data
                        if (isDexEntry(name) && isStandardDex(data)) {
                            maxDexIndex = maxOf(maxDexIndex, dexIndex(name))
                            if (containsDexString(data, TARGET_DESCRIPTOR)) {
                                hasTargetShimClass = true
                            }
                            val patch = patchBuildVersionDescriptor(data)
                            if (patch.count > 0) {
                                outData = patch.bytes
                                patchedDexFiles++
                                patchedReferences += patch.count
                            }
                        }

                        // A transformed APK is a private virtual-runtime artifact; its
                        // original APK signature cannot remain cryptographically valid.
                        // Keep manifest/resources/native payloads, but drop signature
                        // container records so parsers do not mistake stale signatures
                        // for valid ones. BlackBox keeps the app identity virtually.
                        if (patchedReferences > 0 && isApkSignatureArtifact(name)) {
                            continue
                        }

                        output.putNextEntry(ZipEntry(name).apply { time = entry.time })
                        output.write(outData)
                        output.closeEntry()
                    }

                    if (patchedReferences > 0 && !hasTargetShimClass) {
                        val shimName = nextDexName(maxDexIndex)
                        val shimBytes = context.assets.open(SHIM_ASSET).use { it.readBytes() }
                        check(isStandardDex(shimBytes)) { "Legacy SDK shim asset is not a valid DEX." }
                        output.putNextEntry(ZipEntry(shimName))
                        output.write(shimBytes)
                        output.closeEntry()
                    }
                }
            }

            if (patchedReferences == 0) {
                temp.delete()
                return Result(false, 0, 0, null)
            }

            // Replace atomically enough for the private app sandbox. A failed rename
            // falls back to a copy, leaving the source intact until the copy completes.
            val backup = File(apk.parentFile, "${apk.name}.pretranslate")
            if (backup.exists()) backup.delete()
            if (!apk.renameTo(backup)) {
                error("Could not stage APK for guest translation.")
            }
            try {
                if (!temp.renameTo(apk)) {
                    temp.inputStream().use { input ->
                        FileOutputStream(apk, false).buffered(1024 * 1024).use { output ->
                            input.copyTo(output, 1024 * 1024)
                        }
                    }
                    temp.delete()
                }
                backup.delete()
            } catch (t: Throwable) {
                apk.delete()
                backup.renameTo(apk)
                throw t
            }

            val shim = if (hasTargetShimClass) null else nextDexName(maxDexIndex)
            Log.i(
                TAG,
                "Guest SDK identity translated: file=${apk.name} dex=$patchedDexFiles refs=$patchedReferences shim=$shim",
            )
            return Result(true, patchedDexFiles, patchedReferences, shim)
        } catch (t: Throwable) {
            temp.delete()
            Log.e(TAG, "Guest SDK identity translation failed for ${apk.name}", t)
            throw t
        }
    }

    private data class DexPatch(val bytes: ByteArray, val count: Int)

    private fun patchBuildVersionDescriptor(original: ByteArray): DexPatch {
        val data = original.copyOf()
        val stringCount = readIntLe(data, 56)
        val stringIdsOffset = readIntLe(data, 60)
        if (stringCount < 0 || stringIdsOffset < 0 || stringIdsOffset.toLong() + stringCount.toLong() * 4L > data.size) {
            return DexPatch(original, 0)
        }

        val source = SOURCE_DESCRIPTOR.toByteArray(Charsets.UTF_8)
        val target = TARGET_DESCRIPTOR.toByteArray(Charsets.UTF_8)
        var count = 0

        for (index in 0 until stringCount) {
            val idOffset = stringIdsOffset + index * 4
            val stringDataOffset = readIntLe(data, idOffset)
            if (stringDataOffset <= 0 || stringDataOffset >= data.size) continue
            val payloadOffset = skipUleb128(data, stringDataOffset) ?: continue
            if (payloadOffset + source.size >= data.size) continue
            if (matches(data, payloadOffset, source) && data[payloadOffset + source.size] == 0.toByte()) {
                System.arraycopy(target, 0, data, payloadOffset, target.size)
                count++
            }
        }

        if (count == 0) return DexPatch(original, 0)
        repairDexHeader(data)
        return DexPatch(data, count)
    }

    private fun containsDexString(data: ByteArray, value: String): Boolean {
        if (!isStandardDex(data)) return false
        val stringCount = readIntLe(data, 56)
        val stringIdsOffset = readIntLe(data, 60)
        if (stringCount < 0 || stringIdsOffset < 0 || stringIdsOffset.toLong() + stringCount.toLong() * 4L > data.size) {
            return false
        }
        val wanted = value.toByteArray(Charsets.UTF_8)
        for (index in 0 until stringCount) {
            val stringDataOffset = readIntLe(data, stringIdsOffset + index * 4)
            if (stringDataOffset <= 0 || stringDataOffset >= data.size) continue
            val payloadOffset = skipUleb128(data, stringDataOffset) ?: continue
            if (payloadOffset + wanted.size < data.size &&
                matches(data, payloadOffset, wanted) && data[payloadOffset + wanted.size] == 0.toByte()
            ) return true
        }
        return false
    }

    private fun repairDexHeader(data: ByteArray) {
        val sha1 = MessageDigest.getInstance("SHA-1")
        sha1.update(data, 32, data.size - 32)
        val signature = sha1.digest()
        System.arraycopy(signature, 0, data, 12, 20)

        val adler = Adler32()
        adler.update(data, 12, data.size - 12)
        writeIntLe(data, 8, adler.value.toInt())
    }

    private fun skipUleb128(data: ByteArray, offset: Int): Int? {
        var pos = offset
        repeat(5) {
            if (pos >= data.size) return null
            val value = data[pos++].toInt() and 0xff
            if ((value and 0x80) == 0) return pos
        }
        return null
    }

    private fun matches(data: ByteArray, offset: Int, needle: ByteArray): Boolean {
        if (offset < 0 || offset + needle.size > data.size) return false
        for (i in needle.indices) if (data[offset + i] != needle[i]) return false
        return true
    }

    private fun readIntLe(data: ByteArray, offset: Int): Int {
        if (offset < 0 || offset + 4 > data.size) return -1
        return (data[offset].toInt() and 0xff) or
            ((data[offset + 1].toInt() and 0xff) shl 8) or
            ((data[offset + 2].toInt() and 0xff) shl 16) or
            ((data[offset + 3].toInt() and 0xff) shl 24)
    }

    private fun writeIntLe(data: ByteArray, offset: Int, value: Int) {
        data[offset] = value.toByte()
        data[offset + 1] = (value ushr 8).toByte()
        data[offset + 2] = (value ushr 16).toByte()
        data[offset + 3] = (value ushr 24).toByte()
    }

    private fun isStandardDex(data: ByteArray): Boolean =
        data.size > 112 && data[0] == 'd'.code.toByte() && data[1] == 'e'.code.toByte() &&
            data[2] == 'x'.code.toByte() && data[3] == '\n'.code.toByte()

    private fun isDexEntry(name: String): Boolean = Regex("^classes(\\d*)\\.dex$").matches(name)

    private fun dexIndex(name: String): Int {
        val group = Regex("^classes(\\d*)\\.dex$").matchEntire(name)?.groupValues?.getOrNull(1).orEmpty()
        return if (group.isBlank()) 1 else group.toIntOrNull() ?: 1
    }

    private fun nextDexName(maxIndex: Int): String {
        val next = maxOf(1, maxIndex) + 1
        return "classes${next}.dex"
    }

    private fun isApkSignatureArtifact(name: String): Boolean {
        val upper = name.uppercase()
        if (!upper.startsWith("META-INF/")) return false
        return upper.endsWith(".RSA") || upper.endsWith(".DSA") || upper.endsWith(".EC") ||
            upper.endsWith(".SF") || upper == "META-INF/MANIFEST.MF"
    }
}
